_BASE_: ../mpsa_R50_bs32_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2ConvNeXt"
  CONVNEXT:
    IN_CHANNELS: 3
    DEPTHS: [3, 3, 27, 3]
    DIMS: [128, 256, 512, 1024]
    DROP_PATH_RATE: 0.4
    LSIT: 1.0
    OUT_INDICES: [0, 1, 2, 3]
  WEIGHTS: "pretrained_models/convnext/convnext_base_22k_1k_384.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
